---@meta

-- Generated by `cargo run -p remux-daemon --bin gen-lua-meta`.
-- Do not edit by hand.

---@alias RemuxBuiltinAction
---| "split-pane-vertical"
---| "split-pane-horizontal"
---| "focus-pane-left"
---| "focus-pane-down"
---| "focus-pane-up"
---| "focus-pane-right"
---| "kill-pane"
---| "new-window"
---| "next-window"
---| "prev-window"
---| "kill-window"
---| "select-window-1"
---| "select-window-2"
---| "select-window-3"
---| "select-window-4"
---| "select-window-5"
---| "select-window-6"
---| "select-window-7"
---| "select-window-8"
---| "select-window-9"
---| "detach"
---| "open-session-switcher"

---@alias RemuxCommand RemuxBuiltinAction|RemuxOpenWidgetCommand|RemuxSwitchSessionCommand
---@alias RemuxActionResult nil|RemuxCommand|RemuxCommand[]
---@alias RemuxWidgetKind "selector"|"fuzzy-selector"
---@alias RemuxBarComponent "active-session"|"window-list"
---@alias RemuxBarItem string|RemuxBarComponent|fun(): string|nil

---@class RemuxBarStyle
---@field background_fg? integer
---@field background_bg? integer
---@field left_fg? integer
---@field left_bg? integer
---@field center_fg? integer
---@field center_bg? integer
---@field right_fg? integer
---@field right_bg? integer
---@field window_active_fg? integer
---@field window_active_bg? integer
---@field window_inactive_fg? integer
---@field window_inactive_bg? integer
---@field window_muted_fg? integer

---@class RemuxSelectorStyle
---@field title? string
---@field footer? string
---@field scrim_fg? integer
---@field scrim_bg? integer
---@field border_fg? integer
---@field background_fg? integer
---@field background_bg? integer
---@field title_fg? integer
---@field text_fg? integer
---@field selected_fg? integer
---@field selected_bg? integer
---@field footer_fg? integer
---@field empty_fg? integer

---@class RemuxFuzzySelectorStyle
---@field title? string
---@field footer? string
---@field scrim_fg? integer
---@field scrim_bg? integer
---@field border_fg? integer
---@field background_fg? integer
---@field background_bg? integer
---@field title_fg? integer
---@field text_fg? integer
---@field selected_fg? integer
---@field selected_bg? integer
---@field footer_fg? integer
---@field query_fg? integer
---@field query_bg? integer
---@field placeholder_fg? integer
---@field empty_fg? integer

---@class RemuxPaneStyle
---@field active_border_fg? integer
---@field inactive_border_fg? integer

---@class RemuxBarSections
---@field left? RemuxBarItem[]
---@field center? RemuxBarItem[]
---@field right? RemuxBarItem[]

---@alias RemuxWidgetPlacement "overlay"|"dock"

---@alias RemuxDockEdge "top"|"bottom"|"left"|"right"

---@class RemuxBarWidgetSpec
---@field type "bar"
---@field placement? "dock"
---@field edge? RemuxDockEdge
---@field size? integer
---@field enabled? boolean
---@field left? RemuxBarItem[]
---@field center? RemuxBarItem[]
---@field right? RemuxBarItem[]
---@field style? RemuxBarStyle

---@class RemuxSelectorWidgetDefaults
---@field style? RemuxSelectorStyle

---@class RemuxFuzzySelectorWidgetDefaults
---@field style? RemuxFuzzySelectorStyle

---@class RemuxWidgetDefaults
---@field selector? RemuxSelectorWidgetDefaults
---@field fuzzy_selector? RemuxFuzzySelectorWidgetDefaults

---@class RemuxPaneConfig
---@field style? RemuxPaneStyle

---@class RemuxUiConfig
---@field widgets? RemuxWidgetDefaults
---@field panes? RemuxPaneConfig

---@class RemuxWidgetItem
---@field id string
---@field label? string
---@field selected? boolean

---@class RemuxOpenWidgetCommand
---@field type "open_widget"
---@field widget string

---@class RemuxSwitchSessionCommand
---@field type "switch_session"
---@field session string

---@class RemuxSelectorWidgetSpec
---@field type "selector"
---@field placement? "overlay"
---@field title? string
---@field footer? string
---@field style? RemuxSelectorStyle
---@field items fun(): RemuxWidgetItem[]
---@field on_confirm fun(id: string): RemuxActionResult

---@class RemuxFuzzySelectorWidgetSpec
---@field type "fuzzy-selector"
---@field placement? "overlay"
---@field title? string
---@field footer? string
---@field placeholder? string
---@field style? RemuxFuzzySelectorStyle
---@field items fun(): RemuxWidgetItem[]
---@field on_confirm fun(id: string): RemuxActionResult

---@alias RemuxWidgetSpec RemuxBarWidgetSpec|RemuxSelectorWidgetSpec|RemuxFuzzySelectorWidgetSpec

---@class RemuxKeymap
---@field key string
---@field action RemuxBuiltinAction|string
---@field prefix? boolean

---@class RemuxRect
---@field x integer
---@field y integer
---@field width integer
---@field height integer

---@class RemuxPaneState
---@field id integer
---@field is_active boolean
---@field rect RemuxRect

---@class RemuxWindowState
---@field id integer
---@field index integer
---@field name string
---@field is_active boolean
---@field panes RemuxPaneState[]
---@field active_pane RemuxPaneState|nil

---@class RemuxSessionState
---@field id integer
---@field name string
---@field is_current boolean
---@field windows RemuxWindowState[]
---@field current_window RemuxWindowState|nil

---@class RemuxWidgetState
---@field id string
---@field kind RemuxWidgetKind

---@class RemuxStateApi
---@field sessions RemuxSessionState[]
---@field current_session RemuxSessionState|nil
---@field current_window RemuxWindowState|nil
---@field current_pane RemuxPaneState|nil
---@field active_widget RemuxWidgetState|nil
---@field session fun(name_or_id: string|integer): RemuxSessionState|nil
---@field window fun(index_or_id: integer): RemuxWindowState|nil
---@field pane fun(id: integer): RemuxPaneState|nil

---@class RemuxApi
---@field prefix string
---@field keymaps RemuxKeymap[]
---@field actions table<string, fun(): RemuxActionResult>
---@field widgets table<string, RemuxWidgetSpec>
---@field ui RemuxUiConfig
---@field state RemuxStateApi
---@field open_widget fun(widget_id: string): RemuxOpenWidgetCommand
---@field switch_session fun(session_name: string): RemuxSwitchSessionCommand
---@field split_pane_vertical fun(): RemuxBuiltinAction
---@field split_pane_horizontal fun(): RemuxBuiltinAction
---@field focus_pane_left fun(): RemuxBuiltinAction
---@field focus_pane_down fun(): RemuxBuiltinAction
---@field focus_pane_up fun(): RemuxBuiltinAction
---@field focus_pane_right fun(): RemuxBuiltinAction
---@field kill_pane fun(): RemuxBuiltinAction
---@field new_window fun(): RemuxBuiltinAction
---@field next_window fun(): RemuxBuiltinAction
---@field prev_window fun(): RemuxBuiltinAction
---@field kill_window fun(): RemuxBuiltinAction
---@field select_window fun(index: integer): RemuxBuiltinAction
---@field detach fun(): RemuxBuiltinAction
---@field open_session_switcher fun(): RemuxBuiltinAction

---@type RemuxApi
remux = {}
