use std::{fmt::Write as _, fs, path::PathBuf};

use remux_core::config::BuiltinAction;

const BAR_STYLE_FIELDS: &[&str] = &[
    "background_fg",
    "background_bg",
    "left_fg",
    "left_bg",
    "center_fg",
    "center_bg",
    "right_fg",
    "right_bg",
    "window_active_fg",
    "window_active_bg",
    "window_inactive_fg",
    "window_inactive_bg",
    "window_muted_fg",
];

const SELECTOR_STYLE_FIELDS: &[&str] = &[
    "title",
    "footer",
    "scrim_fg",
    "scrim_bg",
    "border_fg",
    "background_fg",
    "background_bg",
    "title_fg",
    "text_fg",
    "selected_fg",
    "selected_bg",
    "footer_fg",
    "empty_fg",
];

const FUZZY_SELECTOR_STYLE_FIELDS: &[&str] = &[
    "title",
    "footer",
    "scrim_fg",
    "scrim_bg",
    "border_fg",
    "background_fg",
    "background_bg",
    "title_fg",
    "text_fg",
    "selected_fg",
    "selected_bg",
    "footer_fg",
    "query_fg",
    "query_bg",
    "placeholder_fg",
    "empty_fg",
];

const PANE_STYLE_FIELDS: &[&str] = &["active_border_fg", "inactive_border_fg"];

pub fn generated_meta_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("daemon crate should live under the workspace root")
        .join("defaults/remux-meta.lua")
}

#[allow(dead_code)]
pub fn write_generated_meta_file() -> std::io::Result<()> {
    fs::write(generated_meta_path(), generate_lua_meta())
}

pub fn generate_lua_meta() -> String {
    let mut out = String::new();

    writeln!(&mut out, "---@meta").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "-- Generated by `cargo run -p remux-daemon --bin gen-lua-meta`."
    )
    .unwrap();
    writeln!(&mut out, "-- Do not edit by hand.").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@alias RemuxBuiltinAction").unwrap();
    for action in BuiltinAction::ALL {
        writeln!(&mut out, "---| \"{}\"", action.config_name()).unwrap();
    }
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "---@alias RemuxCommand RemuxBuiltinAction|RemuxOpenWidgetCommand|RemuxSwitchSessionCommand"
    )
    .unwrap();
    writeln!(&mut out, "---@alias RemuxActionResult nil|RemuxCommand|RemuxCommand[]").unwrap();
    writeln!(&mut out, "---@alias RemuxWidgetKind \"selector\"|\"fuzzy-selector\"").unwrap();
    writeln!(
        &mut out,
        "---@alias RemuxBarComponent \"active-session\"|\"window-list\""
    )
    .unwrap();
    writeln!(
        &mut out,
        "---@alias RemuxBarItem string|RemuxBarComponent|fun(): string|nil"
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    write_integer_style_class(&mut out, "RemuxBarStyle", BAR_STYLE_FIELDS);
    write_string_or_integer_style_class(&mut out, "RemuxSelectorStyle", SELECTOR_STYLE_FIELDS);
    write_string_or_integer_style_class(&mut out, "RemuxFuzzySelectorStyle", FUZZY_SELECTOR_STYLE_FIELDS);
    write_integer_style_class(&mut out, "RemuxPaneStyle", PANE_STYLE_FIELDS);

    writeln!(&mut out, "---@class RemuxBarSections").unwrap();
    writeln!(&mut out, "---@field left? RemuxBarItem[]").unwrap();
    writeln!(&mut out, "---@field center? RemuxBarItem[]").unwrap();
    writeln!(&mut out, "---@field right? RemuxBarItem[]").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@alias RemuxWidgetPlacement \"overlay\"|\"dock\"").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "---@alias RemuxDockEdge \"top\"|\"bottom\"|\"left\"|\"right\""
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxBarWidgetSpec").unwrap();
    writeln!(&mut out, "---@field type \"bar\"").unwrap();
    writeln!(&mut out, "---@field placement? \"dock\"").unwrap();
    writeln!(&mut out, "---@field edge? RemuxDockEdge").unwrap();
    writeln!(&mut out, "---@field size? integer").unwrap();
    writeln!(&mut out, "---@field enabled? boolean").unwrap();
    writeln!(&mut out, "---@field left? RemuxBarItem[]").unwrap();
    writeln!(&mut out, "---@field center? RemuxBarItem[]").unwrap();
    writeln!(&mut out, "---@field right? RemuxBarItem[]").unwrap();
    writeln!(&mut out, "---@field style? RemuxBarStyle").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxSelectorWidgetDefaults").unwrap();
    writeln!(&mut out, "---@field style? RemuxSelectorStyle").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxFuzzySelectorWidgetDefaults").unwrap();
    writeln!(&mut out, "---@field style? RemuxFuzzySelectorStyle").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxWidgetDefaults").unwrap();
    writeln!(&mut out, "---@field selector? RemuxSelectorWidgetDefaults").unwrap();
    writeln!(&mut out, "---@field fuzzy_selector? RemuxFuzzySelectorWidgetDefaults").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxPaneConfig").unwrap();
    writeln!(&mut out, "---@field style? RemuxPaneStyle").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxUiConfig").unwrap();
    writeln!(&mut out, "---@field widgets? RemuxWidgetDefaults").unwrap();
    writeln!(&mut out, "---@field panes? RemuxPaneConfig").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxWidgetItem").unwrap();
    writeln!(&mut out, "---@field id string").unwrap();
    writeln!(&mut out, "---@field label? string").unwrap();
    writeln!(&mut out, "---@field selected? boolean").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxOpenWidgetCommand").unwrap();
    writeln!(&mut out, "---@field type \"open_widget\"").unwrap();
    writeln!(&mut out, "---@field widget string").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxSwitchSessionCommand").unwrap();
    writeln!(&mut out, "---@field type \"switch_session\"").unwrap();
    writeln!(&mut out, "---@field session string").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxSelectorWidgetSpec").unwrap();
    writeln!(&mut out, "---@field type \"selector\"").unwrap();
    writeln!(&mut out, "---@field placement? \"overlay\"").unwrap();
    writeln!(&mut out, "---@field title? string").unwrap();
    writeln!(&mut out, "---@field footer? string").unwrap();
    writeln!(&mut out, "---@field style? RemuxSelectorStyle").unwrap();
    writeln!(&mut out, "---@field items fun(): RemuxWidgetItem[]").unwrap();
    writeln!(&mut out, "---@field on_confirm fun(id: string): RemuxActionResult").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxFuzzySelectorWidgetSpec").unwrap();
    writeln!(&mut out, "---@field type \"fuzzy-selector\"").unwrap();
    writeln!(&mut out, "---@field placement? \"overlay\"").unwrap();
    writeln!(&mut out, "---@field title? string").unwrap();
    writeln!(&mut out, "---@field footer? string").unwrap();
    writeln!(&mut out, "---@field placeholder? string").unwrap();
    writeln!(&mut out, "---@field style? RemuxFuzzySelectorStyle").unwrap();
    writeln!(&mut out, "---@field items fun(): RemuxWidgetItem[]").unwrap();
    writeln!(&mut out, "---@field on_confirm fun(id: string): RemuxActionResult").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "---@alias RemuxWidgetSpec RemuxBarWidgetSpec|RemuxSelectorWidgetSpec|RemuxFuzzySelectorWidgetSpec"
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxKeymap").unwrap();
    writeln!(&mut out, "---@field key string").unwrap();
    writeln!(&mut out, "---@field action RemuxBuiltinAction|string").unwrap();
    writeln!(&mut out, "---@field prefix? boolean").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxRect").unwrap();
    writeln!(&mut out, "---@field x integer").unwrap();
    writeln!(&mut out, "---@field y integer").unwrap();
    writeln!(&mut out, "---@field width integer").unwrap();
    writeln!(&mut out, "---@field height integer").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxPaneState").unwrap();
    writeln!(&mut out, "---@field id integer").unwrap();
    writeln!(&mut out, "---@field is_active boolean").unwrap();
    writeln!(&mut out, "---@field rect RemuxRect").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxWindowState").unwrap();
    writeln!(&mut out, "---@field id integer").unwrap();
    writeln!(&mut out, "---@field index integer").unwrap();
    writeln!(&mut out, "---@field name string").unwrap();
    writeln!(&mut out, "---@field is_active boolean").unwrap();
    writeln!(&mut out, "---@field panes RemuxPaneState[]").unwrap();
    writeln!(&mut out, "---@field active_pane RemuxPaneState|nil").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxSessionState").unwrap();
    writeln!(&mut out, "---@field id integer").unwrap();
    writeln!(&mut out, "---@field name string").unwrap();
    writeln!(&mut out, "---@field is_current boolean").unwrap();
    writeln!(&mut out, "---@field windows RemuxWindowState[]").unwrap();
    writeln!(&mut out, "---@field current_window RemuxWindowState|nil").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxWidgetState").unwrap();
    writeln!(&mut out, "---@field id string").unwrap();
    writeln!(&mut out, "---@field kind RemuxWidgetKind").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxStateApi").unwrap();
    writeln!(&mut out, "---@field sessions RemuxSessionState[]").unwrap();
    writeln!(&mut out, "---@field current_session RemuxSessionState|nil").unwrap();
    writeln!(&mut out, "---@field current_window RemuxWindowState|nil").unwrap();
    writeln!(&mut out, "---@field current_pane RemuxPaneState|nil").unwrap();
    writeln!(&mut out, "---@field active_widget RemuxWidgetState|nil").unwrap();
    writeln!(
        &mut out,
        "---@field session fun(name_or_id: string|integer): RemuxSessionState|nil"
    )
    .unwrap();
    writeln!(
        &mut out,
        "---@field window fun(index_or_id: integer): RemuxWindowState|nil"
    )
    .unwrap();
    writeln!(&mut out, "---@field pane fun(id: integer): RemuxPaneState|nil").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@class RemuxApi").unwrap();
    writeln!(&mut out, "---@field prefix string").unwrap();
    writeln!(&mut out, "---@field keymaps RemuxKeymap[]").unwrap();
    writeln!(&mut out, "---@field actions table<string, fun(): RemuxActionResult>").unwrap();
    writeln!(&mut out, "---@field widgets table<string, RemuxWidgetSpec>").unwrap();
    writeln!(&mut out, "---@field ui RemuxUiConfig").unwrap();
    writeln!(&mut out, "---@field state RemuxStateApi").unwrap();
    writeln!(
        &mut out,
        "---@field open_widget fun(widget_id: string): RemuxOpenWidgetCommand"
    )
    .unwrap();
    writeln!(
        &mut out,
        "---@field switch_session fun(session_name: string): RemuxSwitchSessionCommand"
    )
    .unwrap();
    writeln!(&mut out, "---@field split_pane_vertical fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field split_pane_horizontal fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field focus_pane_left fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field focus_pane_down fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field focus_pane_up fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field focus_pane_right fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field kill_pane fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field new_window fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field next_window fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field prev_window fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field kill_window fun(): RemuxBuiltinAction").unwrap();
    writeln!(
        &mut out,
        "---@field select_window fun(index: integer): RemuxBuiltinAction"
    )
    .unwrap();
    writeln!(&mut out, "---@field detach fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out, "---@field open_session_switcher fun(): RemuxBuiltinAction").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(&mut out, "---@type RemuxApi").unwrap();
    writeln!(&mut out, "remux = {{}}").unwrap();

    out
}

fn write_integer_style_class(out: &mut String, class_name: &str, fields: &[&str]) {
    writeln!(out, "---@class {class_name}").unwrap();
    for field in fields {
        writeln!(out, "---@field {field}? integer").unwrap();
    }
    writeln!(out).unwrap();
}

fn write_string_or_integer_style_class(out: &mut String, class_name: &str, fields: &[&str]) {
    writeln!(out, "---@class {class_name}").unwrap();
    for field in fields {
        let value_type = if matches!(*field, "title" | "footer") {
            "string"
        } else {
            "integer"
        };
        writeln!(out, "---@field {field}? {value_type}").unwrap();
    }
    writeln!(out).unwrap();
}

#[cfg(test)]
mod tests {
    use super::{generate_lua_meta, generated_meta_path};

    #[test]
    fn generated_meta_matches_checked_in_file() {
        let generated = generate_lua_meta();
        let checked_in =
            std::fs::read_to_string(generated_meta_path()).expect("generated Lua metadata file should exist");
        assert_eq!(
            generated, checked_in,
            "defaults/remux-meta.lua is out of date; run `cargo run -p remux-daemon --bin gen-lua-meta`"
        );
    }

    #[test]
    fn generated_meta_contains_runtime_helpers_and_builtin_actions() {
        let generated = generate_lua_meta();
        assert!(generated.contains("---@field state RemuxStateApi"));
        assert!(generated.contains("---@field open_widget fun(widget_id: string): RemuxOpenWidgetCommand"));
        assert!(generated.contains("---| \"split-pane-vertical\""));
        assert!(generated.contains("---| \"open-session-switcher\""));
    }
}
